### ISSUE TITLE
Using 5V from RJ45 to power Omega

### ISSUE THREAD

**Issue by nv1t** [nv1t/standing-desk-interceptor#8]
I want to setup the device inbetween, without adding another powercable. 
The RJ45 has a VDD of 5V, the Omega needs 3.3V.

A power regulator LD1117, should be find.

(Source: https://docs.onion.io/omega2-docs/hardware-prep-no-dock.html)

**Comment by nv1t** [comment]
Tried setting up an interceptor with a halfed interceptor board (works quite nice) and the omega expansion dock.
![IMG_20200330_162803_2](https://user-images.githubusercontent.com/1524118/77924525-09a17280-72a4-11ea-88d7-1ad1c82297d0.jpg)

Problem is: The omega reboots after approx 18-19sec, due to power spike.

The reculator needs two capacitors to `V_in` and `V_out` of the regulator, but don't have them here.

"My recommended spec is input 47uF and output 470uF to handle power inrush demand by Omega2's sudden WiFi power on in around 19-20 seconds into the boot.
Also, do not use thin power supply wires. I recommend minimum of 22 Ga." - (Source: https://community.onion.io/topic/2375/resolved-omega-2-powered-without-dock-shuts-off-after-18s/3)

**Comment by nv1t** [comment]
There's an open ticket for it in omega-docs repository.
It looks like they know this issue (since 2017)

https://github.com/OnionIoT/Onion-Docs/issues/51

**Comment by nv1t** [comment]
I tried with two capacitors 0.1uF `V_in` and 10uF on `V_out`. Stills drops out. Maybe te capacitors are too small? (only ones i had available, which matched the datasheet)

![IMG_20200331_094322_2](https://user-images.githubusercontent.com/1524118/78000452-93991c00-7334-11ea-80b1-2b8c9f9b2c75.jpg)
The angle looks strange. The grey cable is definitily in 3.3V.

Have to increase the capacitors to see if the voltage drop is still there.

thinking about opting for the easier solution just powering it from an external usb power device for now and doing a board switch later.
Interestingly i can run it with 5V from external power supply, but not from the rj45 pins. seem to be to unstable.

**Comment by nv1t** [comment]
The Board Layout as to accommodate a usb-c or usb-micro for powerrail and possible disconnect between the rj45 and powerrail.
This way, the switch between powering the omega with an external powersupply is much easier and no new layout has to be made. 

If the layout works, maybe the usb-c can be dropped in a later stage. (Rev02 maybe)

**Comment by nv1t** [comment]
Pulling power from the main line for the Microcontroller results in a error code from the motor controller, because it draws to much power...

**Comment by fabicodes** [comment]
How much power does an omega board draw? I've tested it with an ESP8266
which didn't cause any issues

**Comment by nv1t** [comment]
If you power it directly from the the 5V without the control panel it does work. having the CP in the loop, it faults out for me. i have to recheck with an esp32. I tested it with a RPi Zero, which was way to power hungry.
